### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by lstep** [robertkrimen/otto#100]
The author (Robert Krimen) hasn't updated the project since September (and, in fact, no real activity since July). I wrote him an email asking for info on otto's status, but didn't get any answer at all.

**Comment by olebedev** [comment]
+1

**Comment by codeskyblue** [comment]
+1

**Comment by trusch** [comment]
+1

**Comment by rsdoiel** [comment]
With four people interested maybe it is time to fork. That way when a fix or improvement is made we can send a pull request to Robert K.  My sense is that this project solves the problem he wrote it for. 

I've used it in some experimental dev tools I wrote and have been happy with it as is.

All the best - Robert D.

**Comment by olebedev** [comment]
@rsdoiel, @trusch, @codeskyblue, @lstep check [this](https://github.com/olebedev/go-duktape) out. Maybe you find it more appropriate.

**Comment by bontibon** [comment]
+1. Hopefully someone with enough free time will be able to take this project over.

**Comment by rsdoiel** [comment]
It has been well over a decade since I was up on writing interpreters and
compilers but I'm happy to coordinate code merges and fixes. It'll give me
an opportunity to improve my Go knowledge and time permitting fix issues
that come up.  I'll refresh my fork and start watching for issues there.
Any objections?

All the best,

Robert D.

**Comment by SchumacherFM** [comment]
How about this [http://felixge.de/2013/03/11/the-pull-request-hack.html](http://felixge.de/2013/03/11/the-pull-request-hack.html)

> Whenever somebody sends you a pull request, give them commit access to your project.
> While it may sound incredible stupid at first, using this strategy will allow you to unleash the true power of Github.

**Comment by rsdoiel** [comment]
Trusting folk often works in my experience and missing test, docs can be
triaged as bugs. Surprisingly though not everyone will want commit access
(ran into this was some node modules). Probably because it implies
continued involvement.  But I think offering it is a great idea.

Given that this is a Go language project the go tool change provides a
easily solution like code formatting or globally fixing names.

All the best,

Robert

On Fri, Jan 16, 2015 at 9:28 PM, Cyrill Schumacher <notifications@github.com

**Comment by eliquious** [comment]
+1

**Comment by guyvdb** [comment]
Is anyone using this in production?

**Comment by fiorix** [comment]
I use this to test things before they go to production and it's very convenient.

**Comment by rsdoiel** [comment]
I embeded it in a simple web server as a prototyping and test tool.

**Comment by SchumacherFM** [comment]
I've also mailed him to different mail addresses that he could add some of the comments as a project collaborator. If there should be no answer within a week then my suggestion is to fork this project into its own organization and mention that in this/a new ticket.

**Comment by robertkrimen** [comment]
Hey Cyril (and others).

Thanks for your interest in keeping this project going. I'll be taking a look shortly at how to continue/adding collaborators/merging pull requests again.

**Comment by SchumacherFM** [comment]
You rock! :+1:

**Comment by emicklei** [comment]
sorry to "bump" the issue again, but I noticed that both the issues and pull requests are still growing in numbers. 

As a grateful user of the package, I would like it see it improve further by taking contributions for fixes and features again. Maybe start a /go-otto or /javascript-otto repository suggested by @SchumacherFM ?

**Comment by guyvdb** [comment]
I am very grateful for the project and am using it more and more. I would also like to "bump" the issue againg.

**Comment by archisgore** [comment]
Same here. Sorry for the bump, but we use otto in production extensively so I have a vested interest in making sure it is stable - if only to keep my service up. There's a lot of pending PRs that need attention.

**Comment by stevenh** [comment]
Project is definitely not dead, there's a few contributors like myself around keeping an eye.

If there's any issues in particular that have been missed, feel free to bump them.
