### ISSUE TITLE
regexp "?!n"  not working with otto

### ISSUE THREAD

**Issue by DimShadoWWW** [robertkrimen/otto#132]
Hello.. i'm trying to run pouchdb with otto but when I tried to run pouchdb with otto, it fails with this error:
```
$ otto pouchdb-4.0.0.min.js 
(anonymous): Line 9:21696 Invalid regular expression: re2: Invalid (?!) <lookahead>
```
this is the line where it fails:
```javascript
a = /^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/;
```
I checked the tests in otto's the source code and there are tests to check "?!" .. in http://www.w3schools.com/jsref/jsref_regexp_nfollow_not.asp  it is a valid syntax .. I can't see any error in the pouchdb's regrex
any thoughts about what is the cause of this error? it is a pouchdb or otto error with the javascript's regex standard ??

**Comment by robertkrimen** [comment]
It's a problem with otto, unfortunately:

https://github.com/robertkrimen/otto#regular-expression-incompatibility

**Comment by julienmoumne** [comment]
Could there be a way to make the regexp engine pluggable?

One could then decide to use https://github.com/dlclark/regexp2

I understand the performance implications of using a PCRE like regexp engine.

But right now, babel-core, because of its use of lookaheads and backreferences (via lodash, js-tokens and minimatch), can not be interpreted by Otto.

Babel could bring ES2015 and other niceties to Otto without relying on nodejs for source code transformation.
