### ISSUE TITLE
React JS

### ISSUE THREAD

**Issue by pjebs** [robertkrimen/otto#195]
@deoxxa Hey Conrad, It's PJ from Melb Golang.

I was wondering if otto was production ready (eg. quick enough) to do server side React.js rendering?

https://github.com/robertkrimen/otto/issues/67

**Comment by stevenh** [comment]
Which enough is always relative, so the best thing is always to test and see if it works for your use case.

**Comment by deoxxa** [comment]
I've used it to render a react application before, it was slower than v8 at actually executing the JavaScript. It was faster overall though (in my limited testing!) because there were no HTTP requests to get all the required data into the react program. As @stevenh says, you'll have to see if it works for you.

Also, the latest react (and babel) won't run in otto because there are some funky regexes in there that otto currently doesn't support.
