### ISSUE TITLE
Error occurs when call otto.ToValue with a map type

### ISSUE THREAD

**Issue by robscc** [robertkrimen/otto#213]
this is my golang code

```golang
package main

import (
	"fmt"
	"github.com/robertkrimen/otto"
)

func main() {
	_, err := otto.ToValue(map[string]interface{}{
		"test": 1,
	})
	if err != nil {
		fmt.Println(err)
	}
}
```

my error output
`
TypeError: invalid value (map): missing runtime: map[test:1] (map[string]interface {})
`

Do you guys have any sugguestions???

**Comment by tyler-sommer** [comment]
The error message is confusing, but it's telling you that it needs an otto runtime to perform the conversion. The solution is to create an otto runtime, then use the runtime's `ToValue()` method.

```go
package main

import (
    "fmt"
    "github.com/robertkrimen/otto"
)

func main() {
    vm := otto.New()
    _, err := vm.ToValue(map[string]interface{}{
        "test": 1,
    })
    if err != nil {
        fmt.Println(err)
    }
}
```

Note how I create a new runtime `vm := otto.New()` and then call `vm.ToValue()` instead of just `otto.ToValue()`.

**Comment by robscc** [comment]
Thx,it helps me
