### ISSUE TITLE
Is the embedded javascript protected along with the golang source when compiled?

### ISSUE THREAD

**Issue by patakijv** [robertkrimen/otto#239]
Is the javascript source that is embedded protected when the golang source is compiled or is it all accessible by dumping strings, etc?

**Comment by dhiltonp** [comment]
It is compiled at run time. Native Golang functions exported to the
environment are pre-compiled.

On Mar 7, 2017 12:37 PM, "John Pataki" <notifications@github.com> wrote:

Is the javascript source that is embedded protected when the golang source
is compiled or is it all accessible by dumping strings, etc?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/robertkrimen/otto/issues/239>, or mute the thread
