### ISSUE TITLE
Object.MarshalJSON

### ISSUE THREAD

**Issue by matwachich** [robertkrimen/otto#262]
Hello!
I think it will be nice if otto.Object satisfies the json.Marshaler interface (like github.com/dop251/goja, file value.go, line 736)

Thanks

**Comment by jwdeitch** [comment]
@matwachich 
Agreed. If you're looking for a hacky workaround, you can try to json.Stringify within the VM - this should produce a byte array output that can be unmarshaled by Golang. Otherwise, you can try to essentially str replace the NaN bytes with 'null' etc.. until it satisfies the spec. 

Not sure if this will be helpful to you, but the former suggestion is the direction I took.

**Comment by snej** [comment]
Just spent the afternoon dealing with this. It's a serious problem if you're passing JSON-derived objects into and out of Otto, e.g.
1. In Go, parse a JSON object into a `map[string]interface{}`
2. Call an Otto function, passing that as a parameter
3. JS code adds a JS array value to the object
4. Back in Go, marshal the map to JSON

After step 4 you'll find that in the JSON string, where that array should be is just `{}`. Nasty.
