### ISSUE TITLE
Using with react use case

### ISSUE THREAD

**Issue by ghost** [robertkrimen/otto#276]
This looks like a great way to combine react with golang in the same process.

Would anyone be able to elaborate on if they have taken this path ?

Thank you in advance

**Comment by deoxxa** [comment]
I have ([see here](https://github.com/deoxxa/react-in-go)), but it's pretty underwhelming. Otto is not very fast if you're just doing a ton of JavaScript execution.

I have another example of doing react in go in my [don](https://github.com/deoxxa/don/tree/master/react) project. In that case, I use duktape or node if it's available. Execution via duktape was around 15x faster, and node is faster still.

**Comment by gedw99** [comment]
Hey Conrad and hello Melbourne !

Duck tape is probably a no go because I am running the golang on mobiles using gomobile. 
I could use xgo to compile for mobile so cgo works with golang on mobiles but life is too short to go down that merry path.

My main architecture is based on native bridge part of react native. So it's not using the server at all.

If I get a demo working I will update this issue with a link.
If you have gone down this path holler.

**Comment by stevenh** [comment]
Seems like this was answered so closing
