### ISSUE TITLE
JSON.stringify produces JSON whose keys are out of order

### ISSUE THREAD

**Issue by donatj** [robertkrimen/otto#311]
`JSON.stringify`'s keys come out in Alphabetical order rather than given order.

This is a pain point when working with an internal tool that cares about key order.

```go
package main

import (
	"fmt"

	"github.com/robertkrimen/otto"
)

func main() {
	vm := otto.New()
	out, _ := vm.Run(`JSON.stringify({
		"name": "donatj/ok",
		"type": "library",
		"authors": []
	}, null, "\t")`)

	fmt.Println(out)
}
```

outputs:

```json
{
        "authors": [],
        "name": "donatj/ok",
        "type": "library"
}
```

expected output:

```json
{
	"name": "donatj/ok",
	"type": "library",
	"authors": []
}
```

**Comment by spinache** [comment]
I think this is actually not a bug but rather a feature and I think it caused by the golang internal hash map implementation. The thing is, many programming languages implementations pass the hash map keys through hash function so the can always get the same memory address (during the same runtime), this function is given a key and random seed (ex. /dev/urandom), the random order of your keys is caused by random seed given to hash function. 
The solution for this problem is trivial, you should store a list of your keys in another variable (lists are guaranteed to keep items order), than when iterating your map you should iterate list and then acces map by current list item

Similar issue in Lua: https://stackoverflow.com/questions/30970034/lua-in-pairs-with-same-order-as-its-written

**Comment by donatj** [comment]
@spinache 

>  is actually not a bug but rather a feature and I think it caused by the golang internal hash map implementation

They are not coming out in *random* order, as one would expect from a golang map, they come out **reliably** in alpha-sorted order.

Something is actively sorting them alphabetically.

Furhter, I disagree that this is not a bug. Reliable hash index order may not be a feature of Go, but it most certainly **is** a feature of JavaScript.

Not respecting it is an incorrect implementation of the ECMA standard.

The spec for [JSON.stringify](https://www.ecma-international.org/ecma-262/5.1/#sec-15.12.3) states: 

> The properties are enumerated in the ascending array index order of their names.

Which to me reads that they should be output in their given order.

> In your example you can create an `__order__` property which value is a []string and it keeps properties order

That doesn't help, at all. The consumer of the JSON that has problems with these coming out of order is outside of my control. Telling said consumer it has to respect a new `__order__` key because  the JavaScript engine I'm using can't output JSON correctly is silly.

**Comment by deoxxa** [comment]
Ahhh, I was with you until you started mis-quoting the spec. The part you pulled that "ascending array index order of their names" thing from is referring to the evaluation order of an array of replacers.

1. 15.12.3 step 11 -> call Str
2. Str step 10.b -> call JO
3. JO step 6.a -> get property names a la Object.keys
4. 15.2.3.14 step 5 -> note no defined order, see note referring to `for-in`
5. 12.6.4 note "The mechanics and order of enumerating the properties (step 6.a in the first algorithm, step 7.a in the second) is not specified."

If you're going to pull out the spec, you gotta make sure you're _right_.

I'd agree that we should try to match the behaviour of other common ES5 engines, since they do go out of their way to preserve key order as definition order, but this behaviour is not _technically_ out of spec.

**Comment by donatj** [comment]
@deoxxa lol, well I found this poking around

https://github.com/robertkrimen/otto/blob/15f95af6e78dcd2030d8195a138bd88d4f403546/builtin_json.go#L285-L286
