### ISSUE TITLE
Support golang Multiple return values

### ISSUE THREAD

**Issue by gosifn** [robertkrimen/otto#94]
The following code panic now. it would be better that return a array when returns Multiple values

```
var hello = func(name string) (string, string) {
    return fmt.Sprintf("Hello World, %s", name), name
}

vm := otto.New()

vm.Set("hello", hello)

value, err := vm.Run(`hello("otto")`)

if err != nil {
    panic(err)
}

fmt.Println(value)
```

**Comment by stevenh** [comment]
I've got a fix for this which returns the values as an array instead of panicing.

It would still be good to add support for so called [destructing assignments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) though.

I'll submit a pull request soon.

**Comment by robertkrimen** [comment]
Yeah, I think the interface between Go <-> JavaScript could probably use some straightening out. It's grown sort-of organically but maybe a clean-sweep is a good idea.

**Comment by stevenh** [comment]
Initial work to support this is provided by: https://github.com/robertkrimen/otto/pull/103

**Comment by stevenh** [comment]
@gosifn does https://github.com/robertkrimen/otto/pull/103 fix your issue?

**Comment by gosifn** [comment]
@stevenh Yes, Cool! Thanks!
